# Generated by Django 4.2.7 on 2023-12-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_remove_cow_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
