# Generated by Django 4.2.7 on 2023-12-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0004_remove_cow_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='last_service_date',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='pregnancy_status',
        ),
    ]
