# Generated by Django 4.2.7 on 2023-12-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0005_remove_cow_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_type',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='cow',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
